---
- hosts: nfs
  become: true
  remote_user: ubuntu
  vars_files:
    - vars/main.yml
  tasks:

    - name: Create a RAID device
      shell: mdadm --create --verbose "{{ raid_dev }}" --level="{{ raid_level }}" --name="{{ raid_name }}" --raid-devices={{ raid_devices | length }} {{ raid_devices | join(' ') }}
    - name: print details
      shell: mdadm --detail "{{raid_dev}}"
    - name: Ensure RAID array is reassembled automatically on boot.
      shell: mdadm --detail --scan | tee -a /etc/mdadm.conf
    - name: update
      shell: update-initramfs -u

    - name: filesystem
      filesystem: fstype="{{filesystem}}" dev=/dev/md0 force=no
    - name: arrays | Mounting Array(s)
      mount: path=/gitlab-data src=/dev/md0 fstype=ext4 state=mounted

    - name: dir
      file: path=/gitlab-data state=directory mode=777 owner=root group=root
    - name: configure nfs  concurrent resource
      lineinfile: path=/etc/default/nfs-kernel-server regexp="^RPCNFSDCOUNT" line="RPCNFSDCOUNT=16"
    - name: new config file
      file: path=/etc/sysctl.d/50-nfs.conf state=touch
    - name: Configure NFS to use more resources
      blockinfile:
        path: /etc/sysctl.d/50-nfs.conf
        block: |
          sunrpc.tcp_slot_table_entries = 128
          sunrpc.tcp_max_slot_table_entries = 128
          net.core.rmem_default = 262144
          net.core.rmem_max = 16777216
          net.core.wmem_default = 262144
          net.core.wmem_max = 16777216
          net.ipv4.tcp_rmem = 4096 262144 16777216
          net.ipv4.tcp_wmem = 4096 262144 16777216
          net.ipv4.tcp_window_scaling = 1
          net.ipv4.tcp_syncookies = 0
          net.ipv4.tcp_timestamps = 0
          net.ipv4.tcp_sack = 0
          net.ipv4.ip_local_port_range = 1024 65000
          fs.inode-max = 128000
          fs.file-max = 64000
    - name: apply new nfs system
      command: sysctl -p
      register: sys_out
    - name: exports template
      template: src=templates/exports.j2 dest=/etc/exports
      notify: restart nfs-server
    - name: export config
      shell: exportfs -a
    - name: restart nfs
      service: name=nfs-kernel-server state=restarted enabled=true

  handlers:
    - name: restart nfs-server
      service: name=nfs service=restarted
